### ISSUE TITLE
Remove explicit reference to imgui in CMake StaticAnalysis module

### ISSUE THREAD

**Issue by salvioli** [cpp-best-practices/cpp_starter_project#140]
The CMake module StaticAnalyzers.cmake IMHO should be as source independent as possible, currently, it has a reference to imgui/lib folder.

**Comment by ddalcino** [comment]
If I'm not mistaken, the CMake code that references `imgui` points to a folder that doesn't exist.

Here's the relevant code in [StaticAnalyzers.cmake](https://github.com/lefticus/cpp_starter_project/blob/master/cmake/StaticAnalyzers.cmake):
```CMake
set(CMAKE_CXX_CPPCHECK
    ${CPPCHECK}
    --suppress=missingInclude
    --enable=all
    --inline-suppr
    --inconclusive
    -i
    ${CMAKE_SOURCE_DIR}/imgui/lib)
```

According to the [cppcheck manpage](https://linux.die.net/man/1/cppcheck), `-i <dir>` means "ignore the path `<dir>`". The variable [`CMAKE_SOURCE_DIR`](https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html) points to "the path to the top level of the source tree", and there is no "imgui" folder at the top level. As far as I can tell, the whole `-i ${CMAKE_SOURCE_DIR}/imgui/lib` argument serves no purpose and should be removed, whether you're using imgui libraries or not.

Am I missing something?

**Comment by salvioli** [comment]
FWIW, I think you are right, I believe that this is just a leftover from refactoring and should be removed.
