### ISSUE TITLE
Transition away from using Travis-CI

### ISSUE THREAD

**Issue by ddalcino** [cpp-best-practices/cpp_starter_project#157]
Travis CI went through a lot of changes last year, and now they provide a finite amount of compute time for open source projects. You cannot renew the number of minutes for open source projects without approval from a human at Travis-CI; otherwise you need a paid account. In my opinion, there's little reason to use Travis for open source anymore, when there are great free multi-platform alternatives like Appveyor and Github Actions.

I think that it's time to remove the Travis .yml file and the Travis CI badge from this project. The Travis builds no longer run properly when you make a PR, and it’s misleading to leave them in the repo.

The code coverage build that runs on Travis is also an issue. I think it should be moved to one of the GH actions.

_Originally posted by @ddalcino in https://github.com/lefticus/cpp_starter_project/issues/150#issuecomment-905750391_

**Comment by lefticus** [comment]
When merging the diffs for master/main lefticus/cpp-best-practices changes I removed the links to travis, since they were completely out of date now.

We do also though need to push to coveralls from github actions / appveyor also
