### ISSUE TITLE
VS Code Quickstart

### ISSUE THREAD

**Issue by ddalcino** [cpp-best-practices/cpp_starter_project#161]
Two of the oldest open PRs that we have, #60 and #99, are attempting to add support for VS Code. I've never used VS Code for C++ before, so I am not sufficiently qualified to review them. My gut instinct is that IDE-specific code does not belong in this project: this project is about C++, not an IDE. Besides, if something goes wrong with the VS Code code (😃), someone has to debug it.

However, I do understand that it's not so trivial to set up VS Code with an existing C++ project. Since this project works as a batteries-included quick-start for C++ in so many other ways, maybe it would be really helpful to add some batteries for VS Code.

If we do add support for VS Code, I would like to make sure that it also works for VSCodium/Code_OSS/ whatever other telemetry-free alternatives people are using these days.

**Comment by Jason5480** [comment]
Adding Cmake presets (https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) instead of VS Code specific json files might be a better alternative. As I can see both VS Code Visual Studio (https://devblogs.microsoft.com/cppblog/cmake-presets-integration-in-visual-studio-and-visual-studio-code/) and CLion (https://www.jetbrains.com/help/clion/cmake-presets.html) already support this. Qt Creator will support it soon (https://bugreports.qt.io/browse/QTCREATORBUG-24555)

**Comment by ddalcino** [comment]
Sounds like a great idea. Can you confirm that this makes it more automatic to set up a project in VS Code? If so, I'd welcome a PR for this.

As far as I can tell, cmake presets require Cmake 3.19 or higher. I'm not sure if we need to raise the minimum Cmake requirements for this; it seems like it should still work if you're not using this particular feature.

**Comment by Jason5480** [comment]
I am in the process of setting it up the CMake presets for VS2022. While  CMake 3.20 is needed we can ship the correct CMake version through conan using build_requires so the upgrade can be done seamlessly. What do you think?

**Comment by ddalcino** [comment]
I think that it would be OK to require CMake 3.20 to use cmake-presets. I would prefer not to push the `cmake_minimum_required` value in the root level `CMakeLists.txt` if we don't have to; I would like as many users as possible to be able to use `cpp_starter_project`, and keeping the CMake requirements down can help us to do that.

Having said that, it's easy to install [the latest version of CMake](https://pypi.org/project/cmake/) using pip in most situations. We already ask our users to install Conan using pip; they should be able to install CMake the same way if they need to. I would prefer not ask Conan to install CMake, if that is what you are suggesting.
