### ISSUE TITLE
Use GitHub Actions for CI and all other checks.

### ISSUE THREAD

**Issue by Caellian** [cpp-best-practices/cpp_starter_project#47]
Hi again,
I finished writing GitHub [workflows on my repo](https://github.com/Caellian/java-decompiler/tree/master/.github/workflows). This is another simple thing for someone else to copy over.
I'd do it, but it requires minor modifications (tweaking test building targets and removing CI_BUILD env var) and I've already spent 15 or so hours in a row working on it so I feel pretty burnt out.

The tweaks that have to be made might be good to also adopt in this project:
- I created a custom target for each type of tests that depends on all corresponding test type targets so that making them doesn't require making code from src dir. Tests will likely depend on it, but it's nice to have a group target you can build.
- CI_BUILD is there to allow in-source builds for the CI as I've disabled them by default. My .gitignore ignores CMakeCache.txt which means that running "cmake ." from the root directory won't cause any damage.

Feel free to copy them over. They're MIT licensed.

Another thing I was considering is separating the "C/C++ CI" action into individual actions for each OS so that it's clearer which build is failing. And maybe modify Linux matrix to continue building with GCC if Clang fails and the other way around.

Caching might be also good to implement as it would reduce time pipelines are running and it's limited (likely a non-issue).

Oh, and, windows build failed due to missing spdlog.h even though conan said it was downloaded fine, probably a hiccup as it worked fine past 2/3 times.

**Comment by lefticus** [comment]
I just merged the PR the enables the Linux workflow, I'll look into your others

**Comment by Caellian** [comment]
Windows build currently seems to be failing because compiler can't find includes provided by conan. Conan output doesn't report any errors. Not sure what is going on and I could've sworn it compiled at least once properly and I changed something in the meantime. I set up a VM locally to test this out further.
