### ISSUE TITLE
Move the fltk/gtkmm/imgui/nana/qt/sdl examples out of this project?

### ISSUE THREAD

**Issue by olafurw** [cpp-best-practices/cpp_starter_project#69]
I see their purpose. To show how you can use this starter project + library X. But if I would pull the starter project, and I'm not using any of these, I'd have to start by deleting these folders.

It's probably more of a philosophy question.

Do you want people to `git clone ...` and not have to do anything extra or something else?

**Comment by ddalcino** [comment]
Yes, you are meant to delete these folders after you have cloned the project. See docs at https://github.com/lefticus/cpp_starter_project#remove-frameworks-youre-not-going-to-use and https://www.youtube.com/watch?v=av0SYeUxVMU.

You do have a point though; it's an unintuitive idea to clone a project and immediately start deleting things. Maybe it would make more sense to maintain ~7 different branches, each targeting a different framework, or none at all, and then users could just clone whichever branch they're most interested in? That could make this project a lot more work to maintain though.

Maybe a `configure.sh` script could be written to automate the removal of unneeded frameworks? It wouldn't be much of a script; removing the frameworks is a trivial task to begin with.

**Comment by Trashcleaner** [comment]
It would be awesome, if these libraries (fltk/gtkmm/imgui/nana/qt/sdl) were supported by Conan. Then to add these libs would be a matter of uncommenting a line in conanfile.txt or something.

**Comment by agauniyal** [comment]
fwiw, imgui is supported by conan.

**Comment by lefticus** [comment]
We've created now the https://github.com/cpp-best-practices/cpp_boilerplate_project, which does not have these extra folders, and is a bare minimum quickstart.

This project will contain a few GUIs that we can get consistently supported across all platforms, and we are creating different `template` projects that are other quick-start tools.
